### PR TITLE
batch install file

### PR DESCRIPTION
**Pull request by Sokoloft**
This is completely optional but I thought of it and had code existing. Would be ideal to be packaged with a release so the user can extract a folder, open it and run the batch file.

Could be expanded on, might do that in the future if its something to be packed with it.

### CODE REVIEW

**Comment by 2bc4** [comment]
I think it's overkill for one file but I'll leave it open in case we need to add more in the future.

**Comment by Sokoloft** [comment]
If the batch is needed now I can change it to make the plugins dir and then copy the file to it. 

As well as with the latest readme. I'd try and change the dir you have listed. So the user can copy and paste it. Then with instructions to create the plugins folder once in the roaming\streamlink dir. So

```C:\Users\%username%\AppData\Roaming\streamlink```

However I think the batch would just be the cleanest way to install it. 🤷

**Comment by 2bc4** [comment]
I'm OK with a batch file now with plugin sideloading, feel free to update the PR. 

>C:\\Users\\%username%\\AppData\\Roaming\\streamlink

I didn't know that variable existed, I'm more of a Linux person 😅. Go ahead and change that as well.

**Comment by Sokoloft** [comment]
Okay. I'll close this since I don't know how to fix the conflicts. Tomorrow I'll add the batch with instructions. You'll want to add it to release so I can use the release URL for the user to download the batch file.

**Comment by 2bc4** [comment]
>You'll want to add it to release so I can use the release URL for the user to download the batch file.

Make this the link: https://github.com/2bc4/streamlink-ttvlol/releases/latest/download/streamlink-ttvlol.zip

I'll make a zip with both files and then upload a release right after merging. That link always points to the latest release.

**Comment by Sokoloft** [comment]
> > You'll want to add it to release so I can use the release URL for the user to download the batch file.
> 
> Make this the link: https://github.com/2bc4/streamlink-ttvlol/releases/latest/download/streamlink-ttvlol.zip
> 
> I'll make a zip with both files and then upload a release right after merging. That link always points to the latest release.

Since it'll just be in a zip release file then. No point. The download here section will just cover that and it'll be in there. I'll separate the windows install sections to automatically and manually like I had in this PR. But won't link to the batch since it'll be in the release zip

**Pull request closed without merging**
